#!/bin/sh
xrandr --output DVI-D-0 --off --output HDMI-0 --off --output DP-5 --off --output DP-4 --mode 3840x2160 --pos 0x900 --rotate normal --output DP-3 --mode 1920x1080 --pos 3840x1504 --rotate normal --output DP-2 --off --output DP-1 --mode 1600x900 --pos 1760x0 --rotate normal --output DP-0 --off
